= Emerald Wallet for Desktop

image:https://img.shields.io/circleci/project/github/ETCDEVTeam/emerald-wallet/master.svg?label=CircleCI[CircleCI branch]
image:https://img.shields.io/travis/ETCDEVTeam/emerald-wallet.svg?label=Travis[Travis (.org)]
image:https://img.shields.io/appveyor/ci/ETCDEVTeam/emerald-wallet/master?label=AppVeyor[AppVeyor branch]
image:https://codecov.io/gh/ETCDEVTeam/emerald-wallet/branch/master/graph/badge.svg[Codecov, link=https://codecov.io/gh/ETCDEVTeam/emerald-wallet]
image:https://img.shields.io/github/license/ETCDEVTeam/emerald-wallet.svg?maxAge=2592000["License", link="https://github.com/ETCDEVTeam/emerald-wallet/blob/master/LICENSE"]


Emerald is a free open source multiplatform desktop cryptocurrency wallet, supports Ethereum, Ethereum Classic and ERC-20 tokens.

Features:

- *Full Node* - automatically connects to a full node running on a local machine
- *Light Node* - when a full node is not feasible, it uses a secure endpoint provided by our servers. All private keys are stored on local machine.
- *Hardware Wallets* - supports hardware wallets such as Ledger Nano to keep private keys in a most safe way. It's recommended to use Ledger Nano S
- *ERC-20 Tokens* - supports major ERC-20 tokens out of box, and a user can enable support for any ERC-20 compatible token in the Wallet by providing an address
- *Secure Key Storage* = stores all private keys either in a local secure vault. Private keys are encrypted and are not transferred to another node even when Light mode is used
- *Multiplatform* - compatible with major OSes, and builds for Windows, Macos and Linux are provided to download


Official website: https://emeraldwallet.io

== Development instructions
The recommended way to assert that you are using the correct version of node is to use https://github.com/nodenv/nodenv[nodenv],
which will shim the `node` and `npm` commands and assert that the `local` version is set to what is
specified in https://github.com/ETCDEVTeam/emerald-wallet/blob/master/.node-version[.node-version].

Once nodenv is installed:

```shell
$ nodenv install
```

The required version of `node` >= `v8`.

=== Dependencies

==== Libs
You need `libudev`, `libusb-1.0-0`, `libusb-1.0-0-dev` installed on Linux

Ubuntu:

```
sudo apt-get install libudev-dev libusb-1.0-0 libusb-1.0-0-dev
```

====  NPM packages

This will install dependencies.


```shell
$ lerna bootstrap
```


==== Emerald Console

If you haven't got `emerald` already installed on your system, you can execute `./dependencies.sh`
to automatically `rustup` and use `cargo` to install `emerald-cli` and move it to the
project's base dir. Note: this command is idempotent __for rust and cargo__ (it won't
try to install cargo if you've already got it), but it will
use cargo's `-f` flag to force install `emerald-cli` and copy that version to the
project directory.


=== Run for development

_Terminal 1_
```shell
= This will begin a live-watching compiler for ./src/ and ./electron/ folders
$ yarn build:all:dev
```

_Terminal 2_
```shell
= This will begin the simulated electron app pulling from those compiled sources.
$ yarn start:electron
```

=== Logs

Electron and Emerald logs persisted in:

 * OSX: `~/Library/Logs/EmeraldWallet/log.log`
 * Linux: `~/.config/EmeraldWallet/log.log`

=== Building alternatively

You can also use a variety of alternate build options, eg.

```
$ yarn build:all:nowatch
```

=== Building distributions in development
You can run a distribution build in your development environment. Assuming
you've already compiled `./src/` and `./electron/`, you'll be able to run:

```
$ npm run dist
```

This command will build for _your current system_. Note that there are configurations for
several systems (OSX, Linux, Windows) specified in the `"build"` field of `package.json`, but the `dist` command will by default only build for the system it's on.

Note: If you're developing on OSX and have a developer signing identity on your machine, you can
optionally disable that with `CSC_IDENTITY_AUTO_DISCOVERY=false`.

OSX is also able to build for Linux. Add `-ml` to that raw command to build for
both OSX and Linux at the same time.

=== Troubleshooting
Some preliminary things to try in case you run into issues:

Clear out any persisted settings or userdata from previous trials
 * OSX: `~/Library/Application Support/EmeraldWallet`
 * Linux: `~/.config/EmeraldWallet`
 * Windows: `%APPDATA%\EmeraldWallet`

== Run tests

```
yarn test:watch
```

or for single run:
```
yarn test
```

== Contact

=== Submit Bug

https://github.com/ETCDEVTeam/emerald-wallet/issues/new

=== Contact Support

https://emeraldwallet.io/support

=== Chat

Chat with us via Gitter: https://gitter.im/etcdev-public/Lobby

=== Submit Security Issue

Email to security@etcdevteam.com


== License

Copyright 2019 ETCDEV GmbH

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
