const ActionTypes = {
  SET_LOCALE_CURRENCY: 'ACCOUNT/SET_LOCALE_CURRENCY',
  EXCHANGE_RATES: 'ACCOUNT/EXCHANGE_RATES',
  SET_SHOW_HIDDEN_ACCOUNTS: 'SETTINGS/SET_SHOW_HIDDEN_ACCOUNTS',
};

export default ActionTypes;
