const ActionTypes = {
    ADDR_BALANCE: 'LEDGER/ADDR_BALANCE',
    ADDR_TXCOUNT: 'LEDGER/ADDR_TXCOUNT',
    ADDR: 'LEDGER/ADDR',
    SET_LIST_HDPATH: 'LEDGER/SET_LIST_HDPATH',
    CONNECTED: 'LEDGER/CONNECTED',
    WATCH: 'LEDGER/WATCH',
    SELECTED: 'LEDGER/SELECTED',
    SET_HDOFFSET: 'LEDGER/SET_HDOFFSET',
    SET_BASEHD: 'LEDGER/SET_BASEHD',
};

export default ActionTypes;
