const ActionTypes = {
  LOADING: 'ADDRESS/LOADING',
  ADD_CONTACT: 'ADDRESS/ADD_ADDRESS',
  DELETE_ADDRESS: 'ADDRESS/DELETE_ADDRESS',
  UPDATE_ADDRESS: 'ADDRESS/UPDATE_ADDRESS',
  SET_BOOK: 'ADDRESS/SET_BOOK',
};

export default ActionTypes;
