const ActionTypes = {
    SET_BALANCE: 'ACCOUNT/SET_BALANCE',
    LOADING: 'ACCOUNT/LOADING',
    ADD_ACCOUNT: 'ACCOUNT/ADD_ACCOUNT',
    SET_LIST: 'ACCOUNT/SET_LIST',
    UPDATE_ACCOUNT: 'ACCOUNT/UPDATE_ACCOUNT',
    IMPORT_WALLET: 'ACCOUNT/IMPORT_WALLET',
    SET_TOKEN_BALANCE: 'ACCOUNT/SET_TOKEN_BALANCE',
};

export default ActionTypes;
