const ActionTypes = {
  SET_BALANCE: 'ACCOUNT/SET_BALANCE',
  LOADING: 'ACCOUNT/LOADING',
  ADD_ACCOUNT: 'ACCOUNT/ADD_ACCOUNT',
  SET_LIST: 'ACCOUNT/SET_LIST',
  SET_HD_PATH: 'ACCOUNT/SET_HD_PATH',
  UPDATE_ACCOUNT: 'ACCOUNT/UPDATE_ACCOUNT',
  IMPORT_WALLET: 'ACCOUNT/IMPORT_WALLET',
  SET_TOKEN_BALANCE: 'ACCOUNT/SET_TOKEN_BALANCE',
  PENDING_BALANCE: 'ACCOUNT/PENDING_BALANCE',
  SEND_TRANSACTION: 'ACCOUNT/SEND_TRANSACTION',
  SET_TXCOUNT: 'ACCOUNT/SET_TXCOUNT',
};

export default ActionTypes;
