const ActionTypes = {
  SET_TOKEN_BALANCE: 'TOKEN/SET_TOKEN_BALANCE',
  SET_TOKENS_BALANCES: 'TOKEN/SET_TOKENS_BALANCES',
  RESET_BALANCES: 'TOKEN/RESET_BALANCES',
  SET_INFO: 'TOKEN/SET_INFO',
  ADD_TOKEN: 'TOKEN/ADD_TOKEN',
  REMOVE_TOKEN: 'TOKEN/REMOVE_TOKEN',
  SET_LIST: 'TOKEN/SET_LIST',
  LOADING: 'TOKEN/LOADING',
};

export default ActionTypes;
