const ActionTypes = {
  SYNCING: 'NETWORK/SYNCING',
  BLOCK: 'NETWORK/BLOCK',
  PEER_COUNT: 'NETWORK/PEER_COUNT',
  SWITCH_CHAIN: 'NETWORK/SWITCH_CHAIN',
  GAS_PRICE: 'NETWORK/GAS_PRICE',
};

export default ActionTypes;
