[package]
name = "persistent-state"
version = "2.8.0"
license = "Apache-2.0"
edition = "2021"
exclude = ["index.node"]

[lib]
crate-type = ["cdylib"]

[dependencies]
#emerald-wallet-state = { path = "../../../../emerald-wallet-state" }
emerald-wallet-state = { git = "https://github.com/emeraldpay/emerald-wallet-state", branch = "master" }
lazy_static = "1.4.0"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
regex = "1"
hex = "0.4.3"
uuid = "^0.8"
chrono = { version = "0.4", features = ["serde"] }
protobuf = { version = "2.25", features = ["with-bytes"] }
neon-frame = "0.1"
neon-frame-macro = "0.1"

[dependencies.neon]
version = "0.10.0"
default-features = false
features = ["napi-6", "channel-api"]
