const ActionTypes = {
  SET_TOKEN_BALANCE: 'ACCOUNT/SET_TOKEN_BALANCE',
  SET_INFO: 'TOKEN/SET_INFO',
  ADD_TOKEN: 'TOKEN/ADD_TOKEN',
  SET_LIST: 'TOKEN/SET_LIST',
  LOADING: 'TOKEN/LOADING',
};

export default ActionTypes;
