const ActionTypes = {
  SET_LOCALE_CURRENCY: 'ACCOUNT/SET_LOCALE_CURRENCY',
  EXCHANGE_RATES: 'ACCOUNT/EXCHANGE_RATES',
  SET_SHOW_HIDDEN_ACCOUNTS: 'SETTINGS/SET_SHOW_HIDDEN_ACCOUNTS',
  NUM_CONFIRMATIONS: 'SETTINGS/NUM_CONFIRMATIONS',
  MODE: 'SETTINGS/MODE',
};

export default ActionTypes;
